# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

inherit_from:
  - .rubocop.rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'doc/**/*'
    - 'Capfile'
    - 'config.ru'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/dummy/db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
