version: 2.1
executors:
  ruby:
    docker:
      - image: cimg/ruby:3.3.4
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASS: postgres
          RAILS_ENV: test
          BUNDLER_VERSION: 2.5.17
      - image: cimg/postgres:12.12
        environment:
          POSTGRES_DB: nexo_test
commands:
  bundle_install:
    description: Install Ruby dependencies with Bundler
    steps:
      - restore_cache:
          keys:
            - bundle-v6-{{ arch }}-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
            - bundle-v6-{{ arch }}-{{ checksum ".ruby-version" }}-

      - run:
          name: Install Ruby Dependencies
          command: |
            gem install bundler -v $BUNDLER_VERSION --conservative --no-document
            gem install overcommit
            bundle config --local deployment true
            bundle config --local path vendor/bundle
            bundle config --local without production
            bundle check || (bundle install --jobs=4 --retry=3 && bundle clean)
      - save_cache:
          paths:
            - ./vendor/bundle
          key: bundle-v6-{{ arch }}-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}

jobs:
  lint-test:
    executor: ruby
    steps:
      - checkout
      - bundle_install
      - run:
          name: Run Overcommit
          command: |
            git config --local user.name "Circle CI"
            git config --local user.email ci@example.com
            overcommit --sign
            overcommit --run

      - run:
          name: Run tests
          command: |
            bundle exec rails db:schema:load
            bundle exec rspec
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory in the execution
          # environment which is taken to be the root directory of the workspace.
          root: coverage
          # Must be relative path from root
          paths:
            - lcov/project.lcov
  coverage:
    executor: ruby
    steps:
      - checkout
      - bundle_install
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: coverage
      - run:
          name: Verify test coverage
          command: |
            bundle exec undercover --compare origin/main
workflows:
  build-test:
    jobs:
      - lint-test
      - coverage:
          requires:
            - lint-test
